name: Build PriyamTV APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Android Project
        run: flutter create . --platforms=android --org=com.priyamtv --project-name=priyamtv

      - name: Force App Name to PriyamTV
        run: |
          sed -i 's/android:label="priyam_tv"/android:label="PriyamTV"/g' android/app/src/main/AndroidManifest.xml

      - name: Fix App Icon (Edge-to-Edge Adaptive Crop)
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          # Crop outer dark vertical canvas and force square
          convert logo.jpeg -gravity Center -crop 700x700+0+0 +repage -resize 512x512 logo_clean.png
          
          # Generate legacy and adaptive launcher drawables
          mkdir -p android/app/src/main/res/mipmap-xxxhdpi
          mkdir -p android/app/src/main/res/mipmap-hdpi
          mkdir -p android/app/src/main/res/mipmap-mdpi
          mkdir -p android/app/src/main/res/mipmap-xhdpi
          mkdir -p android/app/src/main/res/mipmap-xxhdpi

          cp logo_clean.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
          cp logo_clean.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          cp logo_clean.png android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
          cp logo_clean.png android/app/src/main/res/mipmap-mdpi/ic_launcher.png
          cp logo_clean.png android/app/src/main/res/mipmap-hdpi/ic_launcher.png

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PriyamTV-Release
          path: build/app/outputs/flutter-apk/app-release.apk
